[package]
name = "rust-jwt-1"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "8.1.1"
rsa_key = { version = "0.1.0", path = "rsa_key" }
serde = { version = "1.0", features = ["derive"] }

[workspace]
members = [
  "rsa_key",
]
